### ISSUE TITLE
Explorer template does not forward the daemon rpc port

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtoken/0-templates#22] opened 2018-04-25 08:56 UTC
It forwards 80 and 443 to the container to reach the caddy via http/https, but it does not forward the daemon rpc port. As a result, the daemon is not publicly reachable

**Comment by zaibon** [comment] 2018-04-25 09:34
duplicate of #19

**Closed by zaibon** 2018-04-25 09:34 UTC
Labels: priority_major, type_bug
